### PR TITLE
feat: adds MK1 support

### PR DESCRIPTION
**Pull request by tillt**

### CODE REVIEW

**Comment by tillt** [comment]
Releasing alphas from this branch until things are good enough - or never.

**Comment by tillt** [comment]
https://github.com/tillt/KompleteSynthesia/releases/tag/v0.55.0.1

**Comment by daaain** [comment]
Still no joy, the lights just stay blue / purple based on the octave range:

image

**Comment by tillt** [comment]
https://github.com/tillt/KompleteSynthesia/releases/tag/v0.55.0.2

**Comment by tillt** [comment]
However my hopes are not that high. This one ^^ is mostly based on this discussion: https://github.com/ojacques/SynthesiaKontrol/issues/22

**Comment by daaain** [comment]
Amazing, it's finally doing something 🎉 

https://github.com/tillt/KompleteSynthesia/assets/69962/bb032870-4759-4479-a71a-8649cf9154c0

**Comment by tillt** [comment]
omg - that is perfect - this is what I hoped could be the best possible result - et voila.

Now it is time to find proper colour and intensity mapping - we are obviously off with the intensity.

**Comment by tillt** [comment]
I'll be back on this as soon as I have some spare minutes...

**Comment by tillt** [comment]
> Amazing, it's finally doing something 🎉

🎉 
 
> BTW I also got it working with XCode, so can run commits off the branch and you don't necessarily need to build each time!

Nice!

 
>  PXL_20230920_224119004.TS.mp4

What puzzles me is the unpressed state of your lightguide - it is all white. Did you set that up in the KompleteSynthesia `Settings`?

**Comment by daaain** [comment]
> What puzzles me is the unpressed state of your lightguide - it is all white. Did you set that up in the KompleteSynthesia `Settings`?

It's more of a pale yellow, but no, all default colour settings!

**Comment by tillt** [comment]
@daaain give it a spin please - and thanks again for your patience and support.

**Comment by daaain** [comment]
Looking great, the intesity is down and there are different colours so it's already perfectly playable in Synthesia!

The colour selector seems just a bit off though, see video (might have to make it full screen to see my mouse cursor):

https://github.com/tillt/KompleteSynthesia/assets/69962/0cd86a25-0683-4c73-862d-adda5f6665c3

It also crashes when I pick any of the last 5 colours (white or any after) as the index is 17 at this assert:

Screenshot 2023-09-25 at 18 43 41

**Comment by tillt** [comment]
lol about that crash - sorry, a regression

thanks a ton, as always

**Comment by tillt** [comment]
@daaain give it a try, please

**Comment by daaain** [comment]
It's perfect 😻

**Pull request merged**
